apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matching-redis
  namespace: matching
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: matching-redis-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_HOST
      remoteRef:
        key: T3-Wagu-Secrets
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: T3-Wagu-Secrets
        property: REDIS_PORT
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: T3-Wagu-Secrets
        property: REDIS_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: T3-Wagu-Secrets
        property: JWT_SECRET
