apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: game-db
  namespace: game
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: game-db-secret
    creationPolicy: Owner

  data:
    - secretKey: NODE_ENV
      remoteRef:
        key: T3-Wagu-Secrets
        property: NODE_ENV

    - secretKey: GAME_PORT
      remoteRef:
        key: T3-Wagu-Secrets
        property: GAME_PORT

    - secretKey: DB_HOST
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_HOST

    - secretKey: DB_USER
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_USER

    - secretKey: DB_NAME
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_NAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_PASSWORD
