apiVersion: v1
kind: Service
metadata:
  name: matching-svc
  namespace: matching
spec:
  type: ClusterIP
  selector:
    app: matching
  ports:
    - name: http
      port: 80
      targetPort: 3000
