apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matching
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ms-waguwagu/waguwagu-infra
    targetRevision: main
    path: k8s/matching

  destination:
    server: https://kubernetes.default.svc
    namespace: matching

  syncPolicy: {}
  # automated:
  #   prune: true
  #   selfHeal: true
