apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matching-secret
  namespace: matching
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: matching-secret
    creationPolicy: Owner
  data:
    - secretKey: NODE_ENV
      remoteRef:
        key: T3-Wagu-Secrets
        # key: arn:aws:secretsmanager:ap-northeast-2:796973515852:secret:T3-Wagu-Secrets-1jrvWj
        property: NODE_ENV

    - secretKey: REDIS_HOST
      remoteRef:
        key: T3-Wagu-Secrets
        property: REDIS_HOST

    - secretKey: REDIS_PORT
      remoteRef:
        key: T3-Wagu-Secrets
        property: REDIS_PORT

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: T3-Wagu-Secrets
        property: REDIS_PASSWORD

    - secretKey: MATCHING_PORT
      remoteRef:
        key: T3-Wagu-Secrets
        property: MATCHING_PORT

    - secretKey: JWT_SECRET
      remoteRef:
        key: T3-Wagu-Secrets
        property: JWT_SECRET

    - secretKey: DB_HOST
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_HOST

    - secretKey: DB_PORT
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_PORT

    - secretKey: DB_USER
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_PASSWORD

    - secretKey: DB_NAME
      remoteRef:
        key: T3-Wagu-Secrets
        property: DB_NAME

