apiVersion: v1
kind: Service
metadata:
  name: game-gateway
  namespace: game
spec:
  type: ClusterIP
  selector:
    app: game-gateway
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
